# Generated by Django 5.2.7 on 2025-11-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ja', models.CharField(max_length=100)),
                ('title_en', models.CharField(blank=True, max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
                ('school_year', models.IntegerField()),
                ('semester', models.CharField(max_length=20)),
                ('num_credits', models.IntegerField()),
                ('target_grade', models.CharField(max_length=20)),
                ('course_type', models.CharField(max_length=50)),
                ('overview_ja', models.TextField(blank=True)),
                ('overview_en', models.TextField(blank=True)),
                ('prerequisites_ja', models.TextField(blank=True)),
                ('prerequisites_en', models.TextField(blank=True)),
                ('textbook', models.TextField(blank=True)),
                ('reference_book', models.TextField(blank=True)),
                ('grading_policy_ja', models.TextField(blank=True)),
                ('grading_policy_en', models.TextField(blank=True)),
                ('notes_ja', models.TextField(blank=True)),
                ('notes_en', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
